module.exports = {
  Auth: require("./auth.controller"),
  Category: require("./category.controller"),
  Tag: require("./tag.controller"),
  Actor: require("./actor.controller"),
  About: require("./about.controller"),
  TermCondition: require("./termCondition.controller"),
  // Banner: require("./banner.controller"),
  Banner: require("./banner1.controller"),
  FAQs: require("./faqs.controller"),
  Slide: require("./slides.controller"),
  Ads: require("./ads.controller"),
  TopbarContent: require("./topbarContent.controller"),
  ContactForm: require("./contactForm.controller"),
};
